apiVersion: v1
kind: Service
metadata:
  labels:
    app: jekyll
  name: jekyll
  namespace: development
spec:
  ports:
  - name: jekyll-service
    nodePort: 30097
    port: 8080
    protocol: TCP
    targetPort: 4000
  selector:
    app: jekyll
  type: NodePort